
language:
- node_js:
before_install:
  - npm install -g lerna
  - npm install -g nyc
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
install:
  - lerna bootstrap
  - cd packages/etherlime-utils
  - yarn link
  - cd ../..
services:
  - docker
script:
  - etherlime ganache &> /dev/null &
  - sleep 10
  - lerna run test
after_success: 
  - nyc report --reporter=text-lcov > coverage.lcov && codecov