language: phyton
node_js:
  - "8.9.4"
dist: xenial  
python:
  - "3.6" 
install:
  - pip3 install virtualenv
  - npm install
  - npm link
script:
  - etherlime ganache &> /dev/null &
  - sleep 10
  - npm test
after_success: 
  - npm run coverage