language:
- node_js:
before_install:
  - npm install -g lerna
install:
  - lerna bootstrap
  - lerna link
services:
  - docker
script:
  - etherlime ganache &> /dev/null &
  - sleep 10
  - npm test
after_success: 
  - npm run coverage