language: python
node_js:
  - "8.9.4"
dist: xenial
python:
  - "3.6"
install:
  - sudo apt-get install virtualenv
  - which python3
  - virtualenv -p python3 vyper-venv
  - pip install vyper
  - npm install
  - npm link
script:
  - etherlime ganache &> /dev/null &
  - sleep 10
  - npm test
after_success: 
  - npm run coverage