language: node_js
node_js:
  - "8.9.4"
python: "3.7"
dist: xenial
install:
  - pip install virtualenv
  - npm install
  - npm link
script:
  - etherlime ganache &> /dev/null &
  - sleep 10
  - npm test
after_success: 
  - npm run coverage